bigiq_cm_server: 10.1.1.4
# SEA-vBIGIP01.termmarc.com
bigip_target_ip: 10.1.1.7
as3_schemaVersion: 3.7.0
task1_vs: 10.1.10.111
task1_node1: 10.1.20.110
task1_node2: 10.1.20.111
task2_vs: 10.1.10.113
task2_node1: 10.1.20.112
task2_node2: 10.1.20.113
task3a_vs: 10.1.10.123
task3a_node1: 10.1.20.122
task3a_node2: 10.1.20.123
task3a_policyWAF: /Common/templates-default
task3b_vs: 10.1.10.125
task3b_node1: 10.1.20.124
task3b_node2: 10.1.20.125
task4_vs: 10.1.10.127
task4_node1: 10.1.20.126
task4_node2: 10.1.20.127
task5a_vs: 10.1.10.129
task5a_node1: 10.1.20.128
task5a_node2: 10.1.20.129
task5b_vs: 10.1.10.131
task5b_node1: 10.1.20.130
task5b_node2: 10.1.20.131
task6_bigiq_custom_template: HTTPcustomTemplateTask6
task8_vs: 10.1.10.133
task8_node1: 10.1.20.132
task8_node2: 10.1.20.133
task8_bigiq_custom_template: HTTPcustomTemplateTask6
task10_vs: 10.1.10.134
task10_hostname: httpd.apache.org