bigiq_cm_server: 10.192.75.180
bigip_target: bigip1.lab.fp.f5.com
bigip_target_ip: 10.192.75.182
as3_schemaVersion: 3.12.0
task1_vs: 10.1.10.204
task1_node1: 10.1.20.205
task1_node2: 10.1.20.206
task2_vs: 10.1.10.205
task2_node1: 10.1.20.207
task2_node2: 10.1.20.208
task3a_vs: 10.1.10.206
task3a_node1: 10.1.20.209
task3a_node2: 10.1.20.210
task3a_policyWAF: /Common/templates-default
task5a_vs: 10.1.10.215
task5a_node1: 10.1.20.207
task5a_node2: 10.1.20.208
task5b_vs: 10.1.10.216
task5b_node1: 10.1.20.207
task5b_node2: 10.1.20.208