bigiq_cm_server: 10.192.75.185
bigip_target: bigip2.lab.fp.f5.com
bigip_target_ip: 10.192.75.184
as3_schemaVersion: 3.12.0
task1_vs: 10.1.10.210
task1_node1: 10.1.20.205
task1_node2: 10.1.20.206
task2_vs: 10.1.10.211
task2_node1: 10.1.20.207
task2_node2: 10.1.20.208
task3a_vs: 10.1.10.212
task3a_node1: 10.1.20.209
task3a_node2: 10.1.20.210
task3a_policyWAF: /Common/templates-default
task3b_vs: 10.1.10.213
task3b_node1: 10.1.20.209
task3b_node2: 10.1.20.210
task4_vs: 10.1.10.214
task4_node1: 10.1.20.211
task4_node2: 10.1.20.212
task5a_vs: 10.1.10.215
task5a_node1: 10.1.20.207
task5a_node2: 10.1.20.208
task5b_vs: 10.1.10.216
task5b_node1: 10.1.20.207
task5b_node2: 10.1.20.208
task6_bigiq_custom_template: HTTPcustomTemplateTask6
task8_vs: 10.1.10.217
task8_node1: 10.1.20.205
task8_node2: 10.1.20.206
task10_vs: 10.1.10.218
task10_hostname: httpd.apache.org