---
# Creates auto scaling resources on BIG-IQ
- name: Make BIG IQ Auto Scaling Resources
  hosts: bigiq-01
  vars_files:     
    - ./config.yml
  become: root
  tasks:             
    - name: Create resources
      include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating cloud provider
          url: "{{BIGIQ_URI}}/cm/cloud/providers"
          body: >
            {
                "providerType": "Azure",
                "name": "{{CLOUD_PROVIDER_NAME}}",
                "description": "AZURE cloud provider",
                "azureProperties": {
                    "azureCloud": "{{AZURE_BIGIQ_CLOUD}}",
                    "subscriptionId": "{{SUBSCRIPTION_ID}}",
                    "servicePrincipalSecret": "{{SERVICE_PRINCIPAL_SECRET}}",
                    "tenantId": "{{TENANT_ID}}",
                    "clientId": "{{CLIENT_ID}}"
                }
            }

          var_name: cloud_provider_result

    - include_tasks: ./helpers/post.yml
      with_items:
        - name: Creating cloud environment
          url: "{{BIGIQ_URI}}/cm/cloud/environments"
          body: >
            {
                "name": "{{CLOUD_ENVIRONMENT_NAME}}",
                "description": "AZURE cloud environment for DO",
                "providerReference": {
                    "link": "https://localhost/mgmt/cm/cloud/providers/{{cloud_provider_result.id}}"
                },
                "azureProperties": {
                    "location": "{{DEFAULT_LOCATION}}",
                    "mgmtSubnetName": "{{VNET_SUBNET1}}",
                    "vnetName": "{{VNET1}}",
                    "vnetResourceGroupName": "{{PREFIX}}",
                    "sourceAddrRestriction": "*",
                    "moduleSelection": "{{MODULE}}",
                    "licenseType": "BYOL",
                    "imageName": "{{BYOL_BIGIP_NAME}}",
                    "imageOffer": "{{BYOL_BIGIP_OFFER}}",
                    "bigipVersion": "{{BYOL_BIGIP_VERSION}}",
                    "instanceType": "Standard_DS4_v2"
                }
            }

          var_name: cloud_environment_result

...
