---
- name: Wait for DO Task to complete (with retry)
  block:
    - name: Set the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count|int + 1 }}"

    - name: Run check
      uri:
        url: "https://{{ provider.server }}:{{ provider.server_port }}{{ atc_url }}/task/{{ atc_DO_result.json.id }}"
        method: GET
        headers:
          X-F5-Auth-Token: "{{ f5_auth_token }}"
        return_content: true
        validate_certs: "{{ provider.validate_certs }}"
        status_code: 200
      register: atc_DO_status
      #until: atc_DO_status is success
      until: "atc_DO_status is success or atc_DO_status.status == 401"
      retries: "{{ atc_retries }}"
      delay: "{{ atc_delay }}"
      delegate_to: localhost
      when:
        - atc_service == "Device"
        - atc_method == "POST"
  # Rescue block for handling BIG-IQ token timeouts
  rescue:
    - fail:
        msg: Ended after 5 retries
      when: retry_count|int == 5
    
    - debug:
        msg: "caught error: {{ atc_DO_status.json.result.message }}"

    - name: Re authenticate to BIG-IQ
      include_tasks: authentication.yml
      when: atc_DO_status.json.result.message == "Invalid registered claims."

    - name: Redo check
      include_tasks: atc_task_check.yml
