bigiq_onboard_server: 10.192.75.180
bigiq_onboard_hostname: big-iq-cm-01-sjc.lab.fp.f5.com
#bigiq_onboard_discovery_address: 10.1.10.180/24
bigiq_onboard_node_type: cm
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 10.192.50.10
  - 10.192.50.11
bigiq_onboard_dns_search:
  - lab.fp.f5.com
bigiq_onboard_ntp_servers:
  - time.f5.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: S0747-355703-915-8967225-4253130
bigip1: 10.192.75.182
bigip1user: admin
bigip1pass: admin
bigip1conflict: use_bigip
bigip1device_conflict: use_bigip
bigip1versioned_conflict: keep_version
bigip1device_statistics_enable: yes
bigip1device_statistics_interval: 60
bigip1device_statistics_zone: default
bigip1device_statistics_module1: device
bigip1device_statistics_module2: ltm
bigip1modules:
  - ltm
  - asm
  - afm
  - security_shared