bigiq_onboard_server: 10.192.75.186
bigiq_onboard_hostname: big-iq-dcd-01-sjc2.lab.fp.f5.com
#bigiq_onboard_discovery_address: 10.1.10.186/24
bigiq_onboard_node_type: dcd
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 10.192.50.10
  - 10.192.50.11
bigiq_onboard_dns_search:
  - lab.fp.f5.com
bigiq_onboard_ntp_servers:
  - time.f5.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: M1844-306505-184-2111553-4760772

register_dcd_cm_server: 10.192.75.185
register_dcd_dcd_listener: 10.192.75.186
register_dcd_cm_user: admin
register_dcd_cm_password: admin
register_dcd_dcd_user: admin
register_dcd_dcd_password: admin
register_dcd_dcd_services:
  - access
  - dos
  - ipsec
  - afm
  - asm
  - websafe