bigiq_onboard_server: 10.192.75.185
bigiq_onboard_hostname: big-iq-cm-01-sjc2.lab.fp.f5.com
#bigiq_onboard_discovery_address: 10.1.10.185/24
bigiq_onboard_node_type: cm
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: default
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: admin
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 10.192.50.10
  - 10.192.50.11
bigiq_onboard_dns_search:
  - lab.fp.f5.com
bigiq_onboard_ntp_servers:
  - time.f5.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: S0747-355703-915-8967225-4253130
bigip1: 10.192.75.183
bigip1user: admin
bigip1pass: admin
bigip1conflict: use_bigip
bigip1device_conflict: use_bigip
bigip1versioned_conflict: keep_version
bigip1device_statistics_enable: yes
bigip1device_statistics_interval: 60
bigip1device_statistics_zone: default
bigip1device_statistics_module1: device
bigip1device_statistics_module2: ltm
bigip1device_statistics_module3: dns
bigip1cluster: SeattleCluster
bigip1modules:
  - ltm
  - asm
  - afm
  - security_shared
bigip2: 10.192.75.188
bigip2user: admin
bigip2pass: admin
bigip2conflict: use_bigip
bigip2device_conflict: use_bigip
bigip2versioned_conflict: keep_version
bigip2device_statistics_enable: yes
bigip2device_statistics_interval: 60
bigip2device_statistics_zone: default
bigip2device_statistics_module1: device
bigip2device_statistics_module2: ltm
bigip2device_statistics_module3: dns
bigip2cluster: SeattleCluster
bigip2modules:
  - ltm
  - asm
  - afm
  - security_shared
bigip3: 10.192.75.184
bigip3user: admin
bigip3pass: "@dmin1356"
bigip3conflict: use_bigip
bigip3device_conflict: use_bigip
bigip3versioned_conflict: keep_version
bigip3device_statistics_enable: yes
bigip3device_statistics_interval: 60
bigip3device_statistics_zone: default
bigip3device_statistics_module1: device
bigip3device_statistics_module2: ltm
bigip3device_statistics_module3: dns
bigip3cluster: BostonCluster
bigip3modules:
  - ltm
  - asm
  - afm
  - dns
  - security_shared
bigip4: 10.192.75.187
bigip4user: admin
bigip4pass: "@dmin1356"
bigip4conflict: use_bigip
bigip4device_conflict: use_bigip
bigip4versioned_conflict: keep_version
bigip4device_statistics_enable: yes
bigip4device_statistics_interval: 60
bigip4device_statistics_zone: default
bigip4device_statistics_module1: device
bigip4device_statistics_module2: ltm
bigip4device_statistics_module3: dns
bigip4cluster: BostonCluster
bigip4modules:
  - ltm
  - asm
  - afm
  - dns
  - security_shared