bigiq_onboard_server: 10.1.1.13
bigiq_onboard_hostname: big-iq-cm-02.example.com
bigiq_onboard_node_type: cm
bigiq_onboard_discovery_address: 10.1.10.13/24
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: purple123
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: purple123
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.google.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: W7910-531806-979-9214061-0509584