bigiq_onboard_server: 10.1.1.4
bigiq_onboard_hostname: big-iq-cm-01.example.com
bigiq_onboard_node_type: cm
#bigiq_onboard_discovery_address: 10.1.10.4/24
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: purple123
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: purple123
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.google.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: Q0558-866155-422-7867054-4573666
bigip1: 10.1.1.8
bigip1user: admin
bigip1pass: purple123
bigip1conflict: use_bigip
bigip1device_conflict: use_bigip
bigip1versioned_conflict: keep_version
bigip1device_statistics_enable: yes
bigip1device_statistics_interval: 60
bigip1device_statistics_zone: default
bigip1device_statistics_module1: device
bigip1device_statistics_module2: ltm
bigip1device_statistics_module3: dns
bigip1cluster: BostonCluster
bigip1access_conflict_policy: use_bigip
bigip1access_group_first_device: yes
bigip1access_group_name: Boston
bigip1modules:
  - ltm
  - asm
  - afm
  - apm
  - dns
  - security_shared
bigip2: 10.1.1.10
bigip2user: admin
bigip2pass: purple123
bigip2conflict: use_bigip
bigip2device_conflict: use_bigip
bigip2versioned_conflict: keep_version
bigip2device_statistics_enable: yes
bigip2device_statistics_interval: 60
bigip2device_statistics_zone: default
bigip2device_statistics_module1: device
bigip2device_statistics_module2: ltm
bigip2device_statistics_module3: dns
bigip2cluster: BostonCluster
bigip2access_conflict_policy: use_bigip
bigip2access_group_first_device: no
bigip2access_group_name: Boston
bigip2modules:
  - ltm
  - asm
  - afm
  - apm
  - dns
  - security_shared
bigip3: 10.1.1.7
bigip3user: admin
bigip3pass: purple123
bigip3conflict: use_bigip
bigip3device_conflict: use_bigip
bigip3versioned_conflict: keep_version
bigip3device_statistics_enable: yes
bigip3device_statistics_interval: 60
bigip3device_statistics_zone: default
bigip3device_statistics_module1: device
bigip3device_statistics_module2: ltm
bigip3device_statistics_module3: dns
bigip3modules:
  - ltm
  - asm
  - websafe
  - dns
  - afm
  - security_shared
bigip4: 10.1.1.11
bigip4user: admin
bigip4pass: purple123
bigip4conflict: use_bigip
bigip4device_conflict: use_bigip
bigip4versioned_conflict: keep_version
bigip4device_statistics_enable: yes
bigip4device_statistics_interval: 60
bigip4device_statistics_zone: default
bigip4device_statistics_module1: device
bigip4device_statistics_module2: ltm
bigip4modules:
  - ltm
  - asm
  - security_shared