bigiq_onboard_server: 10.1.1.14
bigiq_onboard_hostname: big-iq-dcd-02.example.com
bigiq_onboard_node_type: dcd
bigiq_onboard_discovery_address: 10.1.10.13/24
bigiq_onboard_password: admin
bigiq_onboard_new_root_password: purple123
bigiq_onboard_old_root_password: default
bigiq_onboard_new_admin_password: purple123
bigiq_onboard_old_admin_password: admin
bigiq_onboard_master_passphrase: Thisisthemasterkey#1234
bigiq_onboard_dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4
bigiq_onboard_dns_search:
  - example.com
bigiq_onboard_ntp_servers:
  - time.google.com
bigiq_onboard_timezone: America/Los_Angeles
bigiq_onboard_license_key: B1970-582364-948-9857046-6393697

register_dcd_cm_server: 10.1.1.4
register_dcd_dcd_listener: 10.1.10.14
register_dcd_cm_user: admin
register_dcd_cm_password: purple123
register_dcd_dcd_user: admin
register_dcd_dcd_password: purple123
register_dcd_dcd_services:
  - access
  - dos
  - ipsec
  - afm
  - asm
#  - websafe