##################################################################################################
###########################         UPDATE VARIABLE BELOW          ###############################
##################################################################################################

# Enabling Azure Marketplace images for programmatic access
# On the Azure portal go to All Services
# In the General section, click on Marketplace
# Type in "F5 BIG-IP" in the Search Box to filter the items
# Click on each of the images and do the following
# Click on the "Want to deploy programmatically?"  link on the right
# Click on "Enable" and Save

# Select Azure Cloud for VNET and VPN creation: AzureCloud, AzureChinaCloud, AzureUSGovernment, AzureGermanCloud
AZURE_CLOUD: AzureCloud
# Select Azure Cloud for BIG-IQ SSG: AZURE, AZURE_CHINA, AZURE_US_GOVERNMENT, AZURE_GERMANY
AZURE_BIGIQ_CLOUD: AZURE

SUBSCRIPTION_ID: <Subscription Id>
TENANT_ID: <Tenant Id>
CLIENT_ID: <Client Id>
SERVICE_PRINCIPAL_SECRET: <Service Principal Secret>
# web browser and access token to sign in (if set to yes, delete USERNAME AND PASSWORD variables)
USE_TOKEN: no

# A unique searchable prefix to all resources which are created
# Use a prefix w/o spaces or special characters (not end with - or special characters)
# MUST BE LESS OR EQUAL 15 CHARACTERES
PREFIX: udf-azure-demo
# Also used for the Azure Resource group name

# Select on of  the region below (default East US) - westus, westeurope, eastasia, brazilsouth ...
# run az account list-locations --output table
DEFAULT_LOCATION: eastus

# Adjust the BIG-IP Version based on your region 
BYOL_BIGIP_NAME: "f5-big-all-1slot-byol"
BYOL_BIGIP_OFFER: "f5-big-ip-byol"
BYOL_BIGIP_VERSION: "13.1.304000" # 14.1.206000 / 15.1.004000
MODULE: WAF # LTM OR WAF

##################################################################################################
###############  DO NOT EDIT AFTER THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING  #################
##################################################################################################

# Public IP of SEA-vBIGIP01.termmarc.com, go to Access Methods, e.g. nslookup 49efa5b7-224c-4e7b-9f04-cf52591ec443.access.udf.f5.com)
# The script will get the IP automatically, you should not need to update it.
# dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}'
CUSTOMER_GATEWAY_IP: 0.0.0.0

# VNET cidr block should encompass the subnets you specify
VNET_CIDR_BLOCK: 172.200.0.0/16
SUBNET1_CIDR_BLOCK: 172.200.1.0/24
SUBNET2_CIDR_BLOCK: 172.200.2.0/24
SUBNET3_CIDR_BLOCK: 172.200.255.0/27
SUBNET3_BGP_PEERING: 172.200.255.254
# The VNET and VNET_SUBNET names can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'.
# It may contain word characters or '.', '-', '_'.
VNET1: vnet1demo
VNET_SUBNET1: subnet1demo
VNET_SUBNET2: subnet2demo

EXT_NETWORK_UDF_VPN: 10.1.10.0/24
# BIG-IP Customer gw (Seattle BIG-IP)
EXT_NETWORK_UDF_PEERING: 10.1.10.7
MGT_NETWORK_UDF: 10.1.1.7
LOCAL_GATEWAY: UDF
SHARED_KEY: 4UbtTd2CXf7PJxkt6qgz
ASN1: 65010 #VPN gateway
ASN2: 65020 #local network gateway

IPSEC_DESTINATION_NETWORK: 169.253.1.32
IPSEC_DESTINATION_ADDRESS1: 169.253.1.33
IPSEC_DESTINATION_ADDRESS2: 169.253.1.34
IPSEC_DESTINATION_MASK: 30

BIGIQ_MGT_HOST: 10.1.1.4

# Ubuntu Web Server IP Address (in Subnet 1):
#NODE_NAME: ubuntu
NODE_NAME: "ubuntu{{ lookup('pipe', 'date +%Y%m%d%H') }}"
NODE_ADDRESS: 172.200.1.50
NODE_USER: ubuntu
NODE_PASSWORD: "q6YMum6jG888BFHu"
NODE_PORT: 80
VIRTUAL_SERVER_PORT: 80
POOL_MEMBER_PORT: 80
APPLICATION_BUILDING_SCRIPT: "https://raw.githubusercontent.com/f5devcentral/f5-big-iq-lab/develop/lab/f5-azure-vpn-ssg-6.1.0/arm/init_web.sh"
RESTRICTED_SRC_ADDRESS: "*"

APP_NAME: "{{PREFIX}}-app-azure"

# BIG-IP Customer Gateway Config
ansible_ssh_user: "admin"
ansible_ssh_pass: "purple123"

bigip_rest_user: "admin"
bigip_rest_password: "purple123"

# BIG-IQ SSG CONFIG
BIGIP_USER: adminUser # Username 'admin' is not allowed for role 'Administrator'\"
BIGIP_PWD: "u7BnD@4f5"

BIGIQ_HOST: localhost:8100
BIGIQ_URI: http://{{BIGIQ_HOST}}
BIGIQ_USER: admin
BIGIQ_PWD: "purple123"

# IP Address of BIG IQ setup as license provider
# This BIQ must have netowrk access to the VPC in which the BIG-IP VE will be created
BYOL_BIGIQ_HOST: 10.1.10.4
BYOL_BIGIQ_USER: admin
BYOL_BIGIQ_PWD: "purple123"
#BYOL_POOL_NAME: byol-pool
BYOL_POOL_NAME: byol-pool-perAppVE

PROTOCOL_PROFILE_CLIENT: tcp-lan-optimized
PROTOCOL_PROFILE_SERVER: tcp-lan-optimized
HTTP_PROFILE: http
#Comma separated, string encapsulated list of DNS IP addresses. Leave the outer single quotes in place
NTP_SERVER: time.google.com

SSG_NAME:               "{{PREFIX}}-azure-ssg"
CLOUD_ENVIRONMENT_NAME: "{{PREFIX}}-azure-environment"
CLOUD_PROVIDER_NAME:    "{{PREFIX}}-azure-provider"
DEVICE_TEMPLATE_NAME:   "{{PREFIX}}-azure-device-template"
TEMPLATE_NODE_NAME:     "{{PREFIX}}-azure-service-node"
TEMPLATE_POOL_NAME:     "{{PREFIX}}-azure-pool"
SERVICE_CATALOG_NAME:   "{{PREFIX}}-azure-service-catalog"
LTM_RESOURCE_NAME:      "{{PREFIX}}-azure-resource-name"

# FQDN for APP
APP_FQDN: "{{SSG_NAME}}-{{APP_NAME}}-pip"
