image: "ubuntu:latest"

before_script:
  - apt-get update
  - apt-get install -y python3 python3-dev python3-pip python3-jmespath
  - apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  - pip3 install ansible
  - ansible-galaxy install f5devcentral.atc_deploy --force
  - ansible-galaxy install f5devcentral.bigiq_pinning_deploy_objects --force
  - ansible-galaxy install f5devcentral.bigiq_move_app_dashboard --force
  - ansible-galaxy collection install f5networks.f5_modules

ansible:
  script:
    - ansible-playbook --version
    - pwd
    - ls -lrt
    - ansible-playbook bigiq_waf_policy_and_as3_deploy.yml -i hosts
